// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-M7K6TI_JpjB3tszh6InLsX8LmaaNGPU',
    appId: '1:1032436246033:web:a6926fdbbc310f0a36b3b0',
    messagingSenderId: '1032436246033',
    projectId: 'loginandsignup-6b5c0',
    authDomain: 'loginandsignup-6b5c0.firebaseapp.com',
    storageBucket: 'loginandsignup-6b5c0.appspot.com',
    measurementId: 'G-FXMD5K2GTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD35mVPjSb2G72NmmPQhUsPEHQ7q4JvcZw',
    appId: '1:1032436246033:android:790730a8e22db74436b3b0',
    messagingSenderId: '1032436246033',
    projectId: 'loginandsignup-6b5c0',
    storageBucket: 'loginandsignup-6b5c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu6cMZKbNhVo4IGR175AcQDrCyrYxdRQc',
    appId: '1:1032436246033:ios:ed5ecf7f83a7062836b3b0',
    messagingSenderId: '1032436246033',
    projectId: 'loginandsignup-6b5c0',
    storageBucket: 'loginandsignup-6b5c0.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu6cMZKbNhVo4IGR175AcQDrCyrYxdRQc',
    appId: '1:1032436246033:ios:04c4781ead2b4b9b36b3b0',
    messagingSenderId: '1032436246033',
    projectId: 'loginandsignup-6b5c0',
    storageBucket: 'loginandsignup-6b5c0.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
